services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"] # Uses variables injected by env_file
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
